/**
 * types-data.js
 * 「KAKU ～核～」16 KAKU TYPE 定義データ
 *
 * ここに書かれているタイプ名・コピー・モチーフ・色は【仮実装】です。
 * 設計書の「確定仕様」は次の2点のみです:
 *   1) タイプは CORE6 の「主軸 × 副軸」から機械的に決定される（type-engine.js）
 *   2) 各タイプは KAKU CARD（キャラクター画像 + TYPE SYMBOL + カラー + キャッチコピー）として
 *      結果ページ・SNSシェア・プロフィール・TEAM MAP・MATCH・PERSONAL BOOK で共通利用される
 *
 * タイプの名称・数・コピー文言・カラーは今後変更されても良いようにこの1ファイルへ集約している。
 * （コード側は id で参照するだけで、文言や色を直接埋め込まない）
 */

const KAKU_TYPES = {
  architect: {
    id: "architect",
    nameEn: "ARCHITECT",
    nameJp: "設計者",
    catchcopy: "まだ存在しない答えを、構造からつくる。",
    color: "#4F6D95",
    motif: "幾何学的な設計図・ブループリントの線",
    image: "architect.png",
    weapon: "複雑な物事を整理し、筋の通った設計図に落とし込む力。誰も見えていない全体像を先に描ける。",
    blindSpot: "完璧な構造を求めるあまり、動き出すタイミングを逃しやすい。",
    teamRole: "チームの土台となる仕組みや計画を設計する「設計図担当」。",
    relationStyle: "感情より論理を優先しがちで、距離を詰めるのに時間がかかるが、一度信頼すると長く続く関係を築く。",
    awaken: {
      keywords: ["構造", "静けさ", "先見"],
      sentence: "誰よりも先に、まだない形を思い描いている。",
    },
  },
  pioneer: {
    id: "pioneer",
    nameEn: "PIONEER",
    nameJp: "開拓者",
    catchcopy: "誰も踏み入れていない場所に、最初の一歩を。",
    color: "#C97B4A",
    motif: "コンパスや未開の地図",
    image: "pioneer.png",
    weapon: "前例のない状況でも臆せず動き出せる行動力と好奇心。",
    blindSpot: "新しいことに気を取られ、今あるものを仕上げる前に次へ向かいがち。",
    teamRole: "誰もやったことのない領域を切り拓く「探索担当」。",
    relationStyle: "一緒に新しい体験をすることで距離が縮まるタイプ。ルーティンな関係には物足りなさを感じやすい。",
    awaken: {
      keywords: ["未踏", "好奇心", "一歩目"],
      sentence: "地図にない場所ほど、心が動く。",
    },
  },
  commander: {
    id: "commander",
    nameEn: "COMMANDER",
    nameJp: "指揮官",
    catchcopy: "全体を見渡し、人を動かす。",
    color: "#A6293B",
    motif: "指揮杖・戦略盤の駒",
    image: "commander.png",
    weapon: "状況を俯瞰して的確な判断を下し、人を巻き込みながら前進させる力。",
    blindSpot: "主導権を握りすぎて、周囲の意見を聞き逃すことがある。",
    teamRole: "チーム全体の方向性を決め、動かす「指揮担当」。",
    relationStyle: "頼れる存在として頼られることが多いが、弱さを見せるのは苦手。",
    awaken: {
      keywords: ["統率", "決断", "全体像"],
      sentence: "迷いを断ち切り、進む方向を示す。",
    },
  },
  creator: {
    id: "creator",
    nameEn: "CREATOR",
    nameJp: "創造者",
    catchcopy: "何もないところから、形を生み出す。",
    color: "#7B5EA7",
    motif: "光の粒子が集まって形になる様子",
    image: "creator.png",
    weapon: "既存の枠にとらわれず、自由な発想で新しいものを生み出す想像力。",
    blindSpot: "アイデアが多すぎて、一つのことをやり切るのが苦手なことがある。",
    teamRole: "新しい企画やアイデアの種をまく「発想担当」。",
    relationStyle: "感性で惹かれ合う関係を好み、刺激のないやり取りには退屈しやすい。",
    awaken: {
      keywords: ["発想", "自由", "創造"],
      sentence: "誰も見たことのないものを、思い描ける。",
    },
  },
  strategist: {
    id: "strategist",
    nameEn: "STRATEGIST",
    nameJp: "戦略家",
    catchcopy: "何手も先を読み、勝ち筋を描く。",
    color: "#2C3E63",
    motif: "チェス盤・多層に重なる矢印",
    image: "strategist.png",
    weapon: "情報を整理し、最短距離で目的を達成する筋道を組み立てる力。",
    blindSpot: "考えすぎて動き出すのが遅れたり、感情的な場面で冷たく見られることがある。",
    teamRole: "目的達成までの道筋を組み立てる「戦略担当」。",
    relationStyle: "じっくり信頼を積み重ねるタイプ。表面的な付き合いより、深い対話を好む。",
    awaken: {
      keywords: ["先読み", "論理", "一手"],
      sentence: "感情より、確実な一手を選ぶ。",
    },
  },
  challenger: {
    id: "challenger",
    nameEn: "CHALLENGER",
    nameJp: "挑戦者",
    catchcopy: "壁があるほど、燃える。",
    color: "#E8B930",
    motif: "稲妻・上昇する矢印",
    image: "challenger.png",
    weapon: "困難な状況でこそ力を発揮する突破力と瞬発力。",
    blindSpot: "勢いで動きすぎて、周囲を置き去りにしてしまうことがある。",
    teamRole: "停滞した状況を動かす「突破担当」。",
    relationStyle: "情熱的にぶつかり合うことを恐れない。刺激の少ない関係には物足りなさを感じる。",
    awaken: {
      keywords: ["突破", "瞬発", "情熱"],
      sentence: "壁は、越えるためにある。",
    },
  },
  influencer: {
    id: "influencer",
    nameEn: "INFLUENCER",
    nameJp: "伝道者",
    catchcopy: "言葉と熱量で、人を巻き込む。",
    color: "#E8768A",
    motif: "波紋のように広がる音波や光",
    image: "influencer.png",
    weapon: "自分の想いや考えを言葉にして人の心を動かす表現力。",
    blindSpot: "場の空気や期待に合わせすぎて、本音を後回しにしがち。",
    teamRole: "チームの熱量を高め、外に向けて発信する「伝道担当」。",
    relationStyle: "人を惹きつけるが、深く一対一で向き合う時間も同じくらい大切にしたいタイプ。",
    awaken: {
      keywords: ["発信", "熱量", "共感"],
      sentence: "言葉にした瞬間、想いは力になる。",
    },
  },
  connector: {
    id: "connector",
    nameEn: "CONNECTOR",
    nameJp: "連結者",
    catchcopy: "人と人、点と点をつなぐ。",
    color: "#3AAFA9",
    motif: "結ばれる線・ネットワークのノード",
    image: "connector.png",
    weapon: "異なる立場や考えの人同士を自然につなげる橋渡しの力。",
    blindSpot: "自分自身の意見や欲求を後回しにして、周囲の調整に回りがち。",
    teamRole: "メンバー同士や部署間をつなぐ「連結担当」。",
    relationStyle: "誰とでも自然に打ち解けるが、自分から深く踏み込むのは控えめ。",
    awaken: {
      keywords: ["橋渡し", "調和", "つながり"],
      sentence: "点と点を結ぶと、道になる。",
    },
  },
  navigator: {
    id: "navigator",
    nameEn: "NAVIGATOR",
    nameJp: "案内者",
    catchcopy: "迷う人に、進む方向を示す。",
    // 星座・星のモチーフは占い/スピリチュアル感を避ける方針のため使用しない。
    // 羅針盤＋道しるべ（矢印/標識）という「実用的な方向指示」のモチーフに統一。
    motif: "羅針盤・道しるべの矢印",
    color: "#1F6F6B",
    image: "navigator.png",
    weapon: "相手の状況を見極め、次に進むべき道を示す洞察力。",
    blindSpot: "人を導くことに集中しすぎて、自分自身の進む道を後回しにしがち。",
    teamRole: "メンバーの相談役となり、方向を示す「案内担当」。",
    relationStyle: "聞き役に回ることが多く、頼られることに安心感を覚える。",
    awaken: {
      keywords: ["洞察", "道しるべ", "安心"],
      sentence: "迷いの中に、光を見つける。",
    },
  },
  guardian: {
    id: "guardian",
    nameEn: "GUARDIAN",
    nameJp: "守護者",
    catchcopy: "大切なものを、静かに守る。",
    color: "#3D6B4F",
    motif: "盾・囲む円",
    image: "guardian.png",
    weapon: "変化の中でも変わらない安定感で、周囲を安心させる力。",
    blindSpot: "守ることを優先しすぎて、新しい変化への一歩が遅れがち。",
    teamRole: "チームの基盤や信頼関係を守る「守護担当」。",
    relationStyle: "一度築いた関係を大切に長く育むタイプ。裏切りには強い痛みを感じる。",
    awaken: {
      keywords: ["安定", "献身", "継続"],
      sentence: "変わらずにいることも、一つの強さ。",
    },
  },
  executor: {
    id: "executor",
    nameEn: "EXECUTOR",
    nameJp: "遂行者",
    catchcopy: "決めたことを、最後までやり切る。",
    color: "#5A5F66",
    motif: "歯車・チェックマーク",
    image: "executor.png",
    weapon: "計画を着実に実行し、最後まで責任を持ってやり遂げる力。",
    blindSpot: "予定外の変化への対応が苦手で、柔軟さに欠けることがある。",
    teamRole: "決まったことを確実に形にする「実行担当」。",
    relationStyle: "約束や役割を大切にする誠実なタイプ。裏で手を抜く人には厳しい目を向ける。",
    awaken: {
      keywords: ["実行", "誠実", "完遂"],
      sentence: "積み重ねた先に、確かな結果がある。",
    },
  },
  specialist: {
    id: "specialist",
    nameEn: "SPECIALIST",
    nameJp: "探究者",
    catchcopy: "一つのことを、とことん掘り下げる。",
    color: "#5B3A70",
    motif: "レンズ・掘り下がる螺旋",
    image: "specialist.png",
    weapon: "一つのテーマを深く追求し、他の追随を許さない専門性を築く力。",
    blindSpot: "興味のないことへの関心が薄く、視野が狭くなりがち。",
    teamRole: "専門的な知見でチームを支える「探究担当」。",
    relationStyle: "共通の関心事があると一気に距離が縮まるが、そうでない相手には淡白。",
    awaken: {
      keywords: ["探究", "深度", "専門"],
      sentence: "深く掘るほど、誰にも見えない景色がある。",
    },
  },
  mediator: {
    id: "mediator",
    nameEn: "MEDIATOR",
    nameJp: "調律者",
    catchcopy: "対立の間に立ち、調和を取る。",
    color: "#8FA37E",
    motif: "天秤・調和する波形",
    image: "mediator.png",
    weapon: "異なる意見の間に立ち、双方が納得できる着地点を見つける力。",
    blindSpot: "自分の意見を主張するより、場の調和を優先しすぎることがある。",
    teamRole: "意見の対立を調整し、チームの空気を整える「調律担当」。",
    relationStyle: "争いを避け、穏やかな関係を好む。本音をため込みすぎないよう注意が必要。",
    awaken: {
      keywords: ["調和", "公平", "均衡"],
      sentence: "対立の中にも、着地点はある。",
    },
  },
  builder: {
    id: "builder",
    nameEn: "BUILDER",
    nameJp: "構築者",
    catchcopy: "土台から、着実に積み上げる。",
    color: "#C08A2E",
    motif: "積み上がるブロック・骨組み",
    image: "builder.png",
    weapon: "一つひとつの積み重ねを大切にし、揺るがない土台を作る力。",
    blindSpot: "積み上げるペースが独自で、周囲のスピード感とずれることがある。",
    teamRole: "長期的な仕組みや基盤を作る「構築担当」。",
    relationStyle: "時間をかけて信頼を積み上げるタイプ。急に距離を詰められるのは苦手。",
    awaken: {
      keywords: ["積み上げ", "堅実", "土台"],
      sentence: "一段ずつでも、確実に高くなる。",
    },
  },
  adventurer: {
    id: "adventurer",
    nameEn: "ADVENTURER",
    nameJp: "冒険者",
    catchcopy: "決められた道より、自由な道を選ぶ。",
    color: "#E8703A",
    motif: "分岐する道・地平線",
    image: "adventurer.png",
    weapon: "枠にとらわれず、自分の感覚を信じて進む行動力。",
    blindSpot: "自由を優先しすぎて、周囲との足並みが揃わないことがある。",
    teamRole: "新しい体験や視点をチームに持ち込む「冒険担当」。",
    relationStyle: "束縛を嫌い、自由にお互いを尊重できる関係を好む。",
    awaken: {
      keywords: ["自由", "感覚", "冒険"],
      sentence: "決まった道より、心が動く道を。",
    },
  },
  finisher: {
    id: "finisher",
    nameEn: "FINISHER",
    nameJp: "完遂者",
    catchcopy: "最後の一手まで、責任を持つ。",
    color: "#26456B",
    motif: "ゴールライン・完成した円",
    image: "finisher.png",
    weapon: "物事を最後まで丁寧に仕上げ、完成度を高める粘り強さ。",
    blindSpot: "完成にこだわりすぎて、区切りをつけるタイミングを逃しがち。",
    teamRole: "プロジェクトの仕上げと品質を担う「完遂担当」。",
    relationStyle: "最後まで責任を持って向き合うタイプ。中途半端な関係には落ち着かなさを感じる。",
    awaken: {
      keywords: ["仕上げ", "責任", "完成"],
      sentence: "最後の一手が、すべてを決める。",
    },
  },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { KAKU_TYPES };
}
